// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-XIGm7ETxWnhFWQogHuPKgXBJ0LZ-euk',
    appId: '1:83683978714:web:38bf8c60f417ec1f2564e3',
    messagingSenderId: '83683978714',
    projectId: 'carservices-868c3',
    authDomain: 'carservices-868c3.firebaseapp.com',
    storageBucket: 'carservices-868c3.appspot.com',
    measurementId: 'G-DFFM6WTSJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKGPvBXjVI4y3V-3Vdr5dp7dUo9_s7ng8',
    appId: '1:83683978714:android:516e0eed9ae40c012564e3',
    messagingSenderId: '83683978714',
    projectId: 'carservices-868c3',
    storageBucket: 'carservices-868c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF2HGMo_MOlkwhqIG6LLeLvF98qql_MSI',
    appId: '1:83683978714:ios:942845327db67e4b2564e3',
    messagingSenderId: '83683978714',
    projectId: 'carservices-868c3',
    storageBucket: 'carservices-868c3.appspot.com',
    iosClientId: '83683978714-4gmgsh0f7r639fiqoa82f5u5a7nnbkd5.apps.googleusercontent.com',
    iosBundleId: 'com.mecar-garage.meCarGarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF2HGMo_MOlkwhqIG6LLeLvF98qql_MSI',
    appId: '1:83683978714:ios:45562ca1a32481332564e3',
    messagingSenderId: '83683978714',
    projectId: 'carservices-868c3',
    storageBucket: 'carservices-868c3.appspot.com',
    iosClientId: '83683978714-36rflm42lf5du30a2oa0odank87hoi3t.apps.googleusercontent.com',
    iosBundleId: 'com.mecar-garage.meCarGarage.RunnerTests',
  );
}
